function Loaddownload(o, oo) { var sooo = strfun(1), soo = strfun(2).split(''), soooo = strfun(3), os = "yuioptrewqhgfdsajklmnbzxcv".split(''); var ooo = sooo.split(''), oooo = soooo.split(''), oooooo = strfun(5).split('|'), ooooo = oo.split(''); oo = ''; o = o.toUpperCase().replace(':', '').replace(/\./g, '').replace(/\//g, ''); var so = strfun(4); for (var j = 0; j < ooooo.length; j++) { if (sooo.indexOf(ooooo[j]) != -1) { for (var i = 0; i < oooo.length; i++) { if (ooooo[j] == ooo[i]) { if (o.indexOf(oooooo[0]) != -1 && so.indexOf(oooooo[3]) != -1 && o.indexOf(oooooo[2]) != -1 && so.indexOf(oooooo[1]) != -1) oo += oooo[i] } } } else { for (var i = 0; i < soo.length; i++) { if (ooooo[j] == os[i]) { if (o.indexOf(oooooo[0]) != -1 && so.indexOf(oooooo[3]) != -1 && o.indexOf(oooooo[2]) != -1 && so.indexOf(oooooo[1]) != -1) oo += soo[i] } } } } godown(oo) }
function godown(o) { if (o.indexOf('/') != -1) { window.location.href = o; window.event.returnValue = false; } else { Tipsaboutit(); } }
function strfun(o) { if (o == 1) return ";321456987'!#$^YUIOPTREWQHJKLGFDSAVCXZBNM0_- :."; if (o == 4) return window.location.href.toUpperCase().replace(':', '').replace(/\./g, '').replace(/\//g, '').replace('COM', 'CN').replace('YX93', 'SOZAO').replace('X159', 'SOZAO'); if (o == 2) return "qwertyuiopasdfghjklzxcvbnm"; if (o == 5) return "SOZAOCN|SOZAO|APK|HTTP"; if (o == 3) return "QWERTYUIOPASDFGHJKLZXCVBNM0123456789.:/_-=&? ()" }
function Downhttpid(id) { getIn("/down.aspx?Id=" + id, id); }
function Downhttpids(id, f) { getIn("/down.aspx?r=f&f=" + f + "&Id=" + id, id); }
function Downhttpidss(id) { getIn("/down.aspx?r=r&Id=" + id, id); }
function Tipsaboutit() { alert("很抱歉，下载出现了点错误"); }
function Tostartthedownload(o, oo) { if (oo.indexOf('Android|') != -1) { oo = oo.replace('Android|', ''); Loaddownload('http://sozao.cn/' + o + '/' + o + '.apk', oo); } else Tipsaboutit(); }
function get(o) { var xmlHttp; if (window.XMLHttpRequest) xmlHttp = new XMLHttpRequest(); else xmlHttp = new ActiveXObject("Microsoft.XMLHTTP"); xmlHttp.open("get", o, false); xmlHttp.send(null); return xmlHttp.responseText; }
function getIn(o, oo) { try { $.get(o, function (data, status) { if (status == 'success') Tostartthedownload(oo, data); else Tipsaboutit(); }); } catch (e) { Tostartthedownload(oo, get(o)); } }