package com.muyundefeng.spring.entity;

import java.util.Date;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_Id
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_title
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_release_time
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Date blogReleaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_hits
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogHits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_support
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogSupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_comment_num
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogCommentNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_cateId
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogCateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_wordCount
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogWordcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_isOrigina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private Integer blogIsorigina;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_cite_origina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private String blogCiteOrigina;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_table.blog_content
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_Id
     *
     * @return the value of blog_table.blog_Id
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_Id
     *
     * @param blogId the value for blog_table.blog_Id
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_title
     *
     * @return the value of blog_table.blog_title
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_title
     *
     * @param blogTitle the value for blog_table.blog_title
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_release_time
     *
     * @return the value of blog_table.blog_release_time
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Date getBlogReleaseTime() {
        return blogReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_release_time
     *
     * @param blogReleaseTime the value for blog_table.blog_release_time
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogReleaseTime(Date blogReleaseTime) {
        this.blogReleaseTime = blogReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_hits
     *
     * @return the value of blog_table.blog_hits
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogHits() {
        return blogHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_hits
     *
     * @param blogHits the value for blog_table.blog_hits
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogHits(Integer blogHits) {
        this.blogHits = blogHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_support
     *
     * @return the value of blog_table.blog_support
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogSupport() {
        return blogSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_support
     *
     * @param blogSupport the value for blog_table.blog_support
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogSupport(Integer blogSupport) {
        this.blogSupport = blogSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_comment_num
     *
     * @return the value of blog_table.blog_comment_num
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogCommentNum() {
        return blogCommentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_comment_num
     *
     * @param blogCommentNum the value for blog_table.blog_comment_num
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogCommentNum(Integer blogCommentNum) {
        this.blogCommentNum = blogCommentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_cateId
     *
     * @return the value of blog_table.blog_cateId
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogCateid() {
        return blogCateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_cateId
     *
     * @param blogCateid the value for blog_table.blog_cateId
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogCateid(Integer blogCateid) {
        this.blogCateid = blogCateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_wordCount
     *
     * @return the value of blog_table.blog_wordCount
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogWordcount() {
        return blogWordcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_wordCount
     *
     * @param blogWordcount the value for blog_table.blog_wordCount
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogWordcount(Integer blogWordcount) {
        this.blogWordcount = blogWordcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_isOrigina
     *
     * @return the value of blog_table.blog_isOrigina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public Integer getBlogIsorigina() {
        return blogIsorigina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_isOrigina
     *
     * @param blogIsorigina the value for blog_table.blog_isOrigina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogIsorigina(Integer blogIsorigina) {
        this.blogIsorigina = blogIsorigina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_cite_origina
     *
     * @return the value of blog_table.blog_cite_origina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public String getBlogCiteOrigina() {
        return blogCiteOrigina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_cite_origina
     *
     * @param blogCiteOrigina the value for blog_table.blog_cite_origina
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogCiteOrigina(String blogCiteOrigina) {
        this.blogCiteOrigina = blogCiteOrigina == null ? null : blogCiteOrigina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_table.blog_content
     *
     * @return the value of blog_table.blog_content
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_table.blog_content
     *
     * @param blogContent the value for blog_table.blog_content
     *
     * @mbggenerated Thu Mar 02 14:46:56 CST 2017
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }


}