package com.muyundefeng.spring.entity;

import java.util.List;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classId
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     *
     *
     */

    private List<Student> studentList;

    public List<Student> getStudentList() {
        return studentList;
    }

    public void setStudentList(List<Student> studentList) {
        this.studentList = studentList;
    }

    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.className
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    private String classname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classId
     *
     * @return the value of class.classId
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classId
     *
     * @param classid the value for class.classId
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.className
     *
     * @return the value of class.className
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.className
     *
     * @param classname the value for class.className
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }
}