package com.muyundefeng.spring.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.blog_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.commnet_user
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    private String commnetUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_time
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    private Date commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_content
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_id
     *
     * @return the value of blog_comment.comment_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_id
     *
     * @param commentId the value for blog_comment.comment_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.blog_id
     *
     * @return the value of blog_comment.blog_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.blog_id
     *
     * @param blogId the value for blog_comment.blog_id
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.commnet_user
     *
     * @return the value of blog_comment.commnet_user
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public String getCommnetUser() {
        return commnetUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.commnet_user
     *
     * @param commnetUser the value for blog_comment.commnet_user
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public void setCommnetUser(String commnetUser) {
        this.commnetUser = commnetUser == null ? null : commnetUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_time
     *
     * @return the value of blog_comment.comment_time
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_time
     *
     * @param commentTime the value for blog_comment.comment_time
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_content
     *
     * @return the value of blog_comment.comment_content
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_content
     *
     * @param commentContent the value for blog_comment.comment_content
     *
     * @mbggenerated Fri Mar 03 19:12:38 CST 2017
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
}