package com.muyundefeng.spring.entity;

public class Personinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personinfo.ID
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personinfo.home_address
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    private String homeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personinfo.family_number
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    private String familyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personinfo.language
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    private String language;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personinfo.ID
     *
     * @return the value of personinfo.ID
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personinfo.ID
     *
     * @param id the value for personinfo.ID
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personinfo.home_address
     *
     * @return the value of personinfo.home_address
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personinfo.home_address
     *
     * @param homeAddress the value for personinfo.home_address
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personinfo.family_number
     *
     * @return the value of personinfo.family_number
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public String getFamilyNumber() {
        return familyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personinfo.family_number
     *
     * @param familyNumber the value for personinfo.family_number
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public void setFamilyNumber(String familyNumber) {
        this.familyNumber = familyNumber == null ? null : familyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personinfo.language
     *
     * @return the value of personinfo.language
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personinfo.language
     *
     * @param language the value for personinfo.language
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }
}