package com.muyundefeng.spring.entity;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sno
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private Integer sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classId
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private Class ofClass;

    public Class getOfClass() {
        return ofClass;
    }

    public void setOfClass(Class ofClass) {
        this.ofClass = ofClass;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sname
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.dept
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birth
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    private Date birth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sno
     *
     * @return the value of student.sno
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sno
     *
     * @param sno the value for student.sno
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sname
     *
     * @return the value of student.sname
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sname
     *
     * @param sname the value for student.sname
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.dept
     *
     * @return the value of student.dept
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.dept
     *
     * @param dept the value for student.dept
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birth
     *
     * @return the value of student.birth
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birth
     *
     * @param birth the value for student.birth
     *
     * @mbggenerated Mon Mar 06 17:57:36 CST 2017
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }
}