package com.muyundefeng.spring.mapper;

import com.muyundefeng.spring.entity.Article;

import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Fri Feb 24 16:38:45 CST 2017
     */
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Fri Feb 24 16:38:45 CST 2017
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Fri Feb 24 16:38:45 CST 2017
     */
    Article selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Fri Feb 24 16:38:45 CST 2017
     */
    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Fri Feb 24 16:38:45 CST 2017
     */
    int updateByPrimaryKey(Article record);
}