package com.muyundefeng.spring.mapper;

import com.muyundefeng.spring.entity.Class;
import java.util.List;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int deleteByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    Class selectByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    List<Class> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int updateByPrimaryKey(Class record);
}