package com.muyundefeng.spring.mapper;

import com.muyundefeng.spring.entity.Clazz;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int deleteByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    Clazz selectByPrimaryKey(Integer classid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    List<Class> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 06 19:15:49 CST 2017
     */
    int updateByPrimaryKey(Class record);

    Clazz selectByIf(Integer classID);

    @Select("select * from class where classId=#{id}")
    Clazz getOneClazz(@Param("id")Integer id);
}