package com.muyundefeng.spring.mapper;

import com.muyundefeng.spring.entity.Personinfo;
import java.util.List;

public interface PersoninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    int insert(Personinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    Personinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    List<Personinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personinfo
     *
     * @mbggenerated Thu Feb 16 17:53:35 CST 2017
     */
    int updateByPrimaryKey(Personinfo record);
}